openapi: 3.0.0
info:
  title: Addresses
  version: '1.0'
  description: |-
    # What are Addresses?
    Addresses represent one of the many shipping locations a customer can have. An address is created when a customer purchases a subscription. [Subscriptions](https://recharge.stoplight.io/docs/shop-docs/docs/subscriptions.md) are tied to a given address. Each customer can have multiple address objects in a many-to-one relationship. You can override shipping rates using this endpoint.
servers:
  - url: 'https://api.rechargeapps.com/addresses'
paths:
  '':
    get:
      summary: List addresses
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  address:
                    type: object
                    properties:
                      id:
                        type: number
                      customer_id:
                        type: number
                      address1:
                        type: string
                        minLength: 1
                      address2:
                        type: string
                        minLength: 1
                      city:
                        type: string
                        minLength: 1
                      company:
                        type: string
                        minLength: 1
                      country:
                        type: string
                        minLength: 1
                      created_at:
                        type: string
                        minLength: 1
                      discounts:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        items:
                          required:
                            - id
                          properties:
                            id:
                              type: number
                      first_name:
                        type: string
                        minLength: 1
                      last_name:
                        type: string
                        minLength: 1
                      note_attributes:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        items:
                          required:
                            - name
                            - value
                          properties:
                            name:
                              type: string
                              minLength: 1
                            value:
                              type: string
                              minLength: 1
                      order_note:
                        type: string
                        minLength: 1
                      phone:
                        type: string
                        minLength: 1
                      province:
                        type: string
                        minLength: 1
                      shipping_lines_override:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        items:
                          required:
                            - code
                            - price
                            - title
                          properties:
                            code:
                              type: string
                              minLength: 1
                            price:
                              type: string
                              minLength: 1
                            title:
                              type: string
                              minLength: 1
                      updated_at:
                        type: string
                        minLength: 1
                      zip:
                        type: string
                        minLength: 1
                    required:
                      - id
                      - customer_id
                      - address1
                      - address2
                      - city
                      - company
                      - country
                      - created_at
                      - discounts
                      - first_name
                      - last_name
                      - note_attributes
                      - order_note
                      - phone
                      - province
                      - shipping_lines_override
                      - updated_at
                      - zip
                required:
                  - address
              examples: {}
      operationId: get-addresses
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples: {}
      description: ''
    post:
      summary: Create an address
      tags: []
      responses: {}
      operationId: post-addresses
    parameters: []
  '/:id':
    get:
      summary: Retrieve an address
      tags: []
      responses: {}
      operationId: get-id
    put:
      summary: Update an address
      tags: []
      responses: {}
      operationId: put-id
    delete:
      summary: Delete an address
      tags: []
      responses: {}
      operationId: delete-id
    parameters: []
  /count:
    get:
      summary: Count addresses
      tags: []
      responses: {}
      operationId: get-count
  /validate:
    post:
      summary: Validate an address
      tags: []
      responses: {}
      operationId: post-validate
components:
  schemas: {}
  responses: {}
