openapi: 3.0.0
info:
  title: Addresses
  version: '1.0'
  description: |-
    # What are Addresses?
    Addresses represent one of the many shipping locations a customer can have. An address is created when a customer purchases a subscription. [Subscriptions](https://recharge.stoplight.io/docs/shop-docs/docs/subscriptions.md) are tied to a given address. Each customer can have multiple address objects in a many-to-one relationship. You can override shipping rates using this endpoint.
servers:
  - url: 'https://api.rechargeapps.com/addresses'
paths:
  '':
    get:
      summary: List addresses
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  address:
                    type: object
                    properties:
                      id:
                        type: number
                      customer_id:
                        type: number
                      address1:
                        type: string
                        minLength: 1
                      address2:
                        type: string
                        minLength: 1
                      city:
                        type: string
                        minLength: 1
                      company:
                        type: string
                        minLength: 1
                      country:
                        type: string
                        minLength: 1
                      created_at:
                        type: string
                        minLength: 1
                      discounts:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        items:
                          required:
                            - id
                          properties:
                            id:
                              type: number
                      first_name:
                        type: string
                        minLength: 1
                      last_name:
                        type: string
                        minLength: 1
                      note_attributes:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        items:
                          required:
                            - name
                            - value
                          properties:
                            name:
                              type: string
                              minLength: 1
                            value:
                              type: string
                              minLength: 1
                      order_note:
                        type: string
                        minLength: 1
                      phone:
                        type: string
                        minLength: 1
                      province:
                        type: string
                        minLength: 1
                      shipping_lines_override:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        items:
                          required:
                            - code
                            - price
                            - title
                          properties:
                            code:
                              type: string
                              minLength: 1
                            price:
                              type: string
                              minLength: 1
                            title:
                              type: string
                              minLength: 1
                      updated_at:
                        type: string
                        minLength: 1
                      zip:
                        type: string
                        minLength: 1
                    required:
                      - id
                      - customer_id
                      - address1
                      - address2
                      - city
                      - company
                      - country
                      - created_at
                      - discounts
                      - first_name
                      - last_name
                      - note_attributes
                      - order_note
                      - phone
                      - province
                      - shipping_lines_override
                      - updated_at
                      - zip
                required:
                  - address
              examples:
                Example:
                  value:
                    address:
                      id: 0
                      customer_id: 0
                      address1: string
                      address2: string
                      city: string
                      company: string
                      country: string
                      created_at: string
                      discounts:
                        - id: 0
                      first_name: string
                      last_name: string
                      note_attributes:
                        - name: string
                          value: string
                      order_note: string
                      phone: string
                      province: string
                      shipping_lines_override:
                        - code: string
                          price: string
                          title: string
                      updated_at: string
                      zip: string
      operationId: get-addresses
      description: Retrieves a list of addresses tied to a ReCharge store.
    post:
      summary: Create an address
      tags: []
      responses: {}
      operationId: post-addresses
      description: Creates a new address for a customer.
    parameters: []
  '/:id':
    get:
      summary: Retrieve an address
      tags: []
      responses: {}
      operationId: get-id
      description: Retrieves address for a customer based on ID.
    put:
      summary: Update an address
      tags: []
      responses: {}
      operationId: put-id
      description: Updates the specified address.
    delete:
      summary: Delete an address
      tags: []
      responses: {}
      operationId: delete-id
      description: Deletes the specified address.
    parameters: []
  /count:
    get:
      summary: Count addresses
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  count:
                    type: integer
      operationId: get-count
      description: Retrieves a count of addresses.
  /validate:
    post:
      summary: Validate an address
      tags: []
      responses:
        '200':
          description: OK
      operationId: post-validate
      description: |-
        Checks if an address is valid.

        **NOTE:** Address validation only works with United States addresses. At this time we do not validate the `address1` attribute.
components:
  schemas: {}
  responses: {}
